### ISSUE TITLE
分享到QQ空间时失败，找了一下午定位了错误但没学过java不知道怎么修改

### ISSUE THREAD

**Issue by baicie** [haxibiao/react-native-qq-lib#11]
.android.content.ActivityNotFoundException: Unable to find explicit activity class {com.qzone/com.qzonex.module.operation.ui.QZonePublishMoodActivity}; have you declared this activity in your AndroidManifest.xml?
分享到QQ好友是没有问题的，但是分享到空间就一直失败
 else if (scene == 1) {
                    componentName = new ComponentName("com.qzone",
                            "com.qzonex.module.operation.ui.QZonePublishMoodActivity");
                }
当走到这个分支的时候会出现开头的错误

**Comment by PBK-B** [comment]
@baicie 你手机里安装了 QQ 空间客户端吗？

**Comment by baicie** [comment]
谢谢已经解决，我以为是分享到QQ客户端中的QQ空间

**Comment by PBK-B** [comment]
> 谢谢已经解决，我以为是分享到QQ客户端中的QQ空间

这个我觉得可以弄一个分享到 QQ 动态
