### ISSUE TITLE
QQ分享图片分享png格式会转成jpg

### ISSUE THREAD

**Issue by zff1** [haxibiao/react-native-qq-lib#13]
请问可以分享png格式的图片吗

**Comment by PBK-B** [comment]
> 请问可以分享png格式的图片吗

android 还是 ios，我这边看看

**Comment by zff1** [comment]
android和ios好像都会变成jpg,麻烦了

**Comment by PBK-B** [comment]
> android和ios好像都会变成jpg,麻烦了

我这边测试了透明的 gif 和 png 发送之后打开图片还是显示为透明背景，你那个如果是网络图片的话可以检查一下是不是下载的时候出现问题了

分享效果图：
<img height ="260" src="https://user-images.githubusercontent.com/39079814/127481981-31885781-a2ec-4767-8880-643c8cdb34ef.jpeg" />

分享之后打开效果图：
<img height="260" src="https://user-images.githubusercontent.com/39079814/127481988-4ed6f1a0-d590-4ca4-abc2-6cb3ac57b2a3.jpg" />

**Comment by zff1** [comment]
这边是分享什么格式就是什么格式吗？我这边是网图下载为png格式，分享到QQ上是jpg格式，在QQ上看没问题，但在文件管理中查看就是有背景颜色的。

**Comment by zff1** [comment]
我想知道是不能分享png格式的图片吗？还是我的操作有问题

**Comment by zff1** [comment]
const data = {
        type: 'image',
        imageUrl: "file://"+res.path(),
        imageLocalUrl: "file://"+res.path(),
      };
//res.path()是这个 /data/user/0/com.xxxxx/files/xxxxx.png
      QQAPI.shareToQQ(data).then((res: any) => {
       
      });

**Comment by PBK-B** [comment]
> 这边是分享什么格式就是什么格式吗？我这边是网图下载为png格式，分享到QQ上是jpg格式，在QQ上看没问题，但在文件管理中查看就是有背景颜色的。

@zff1 QQ 中看没问题的话，可能是没有保存原图

**Comment by PBK-B** [comment]
@zff1  要不你录屏看看吧，我感觉这不是 SDK 的问题…
