### ISSUE TITLE
 library not found for -lRCTQQAPI

### ISSUE THREAD

**Issue by Zhou-Bill** [haxibiao/react-native-qq-lib#16]
我xcode 运行报错了，没有找到这个包

**Comment by PBK-B** [comment]
@Zhou-Bill 执行一下 `pod install`  试试？

**Comment by Zhou-Bill** [comment]
> @Zhou-Bill 执行一下 `pod install` 试试？

执行过了，是不是需要跟 react-native-qq 这么配，但是不清楚什么原因

**Comment by PBK-B** [comment]
> > @Zhou-Bill 执行一下 `pod install` 试试？
> 
> 执行过了，是不是需要跟 react-native-qq 这么配，但是不清楚什么原因

发一下错误截图看看
