### ISSUE TITLE
【help】引入跟友盟分享sdk冲突

### ISSUE THREAD

**Issue by AlanWen2016** [haxibiao/react-native-qq-lib#17]
求助各路大佬指点下
`/app/android/app/src/debug/AndroidManifest.xml:39:13-74 Error:
        Attribute activity#com.tencent.connect.common.AssistActivity@configChanges value=(orientation|keyboardHidden|screenSize) from [:react-native-qq-lib] AndroidManifest.xml:39:13-74
        is also present at [com.umeng.umsdk:share-qq:7.1.4] AndroidManifest.xml:27:13-63 value=(orientation|keyboardHidden).
        Suggestion: add 'tools:replace="android:configChanges"' to <activity> element at AndroidManifest.xml:37:9-40:75 to override.
`

**Comment by star-heng** [comment]
```
Suggestion: add 'tools:replace="android:configChanges"' to <activity> element at AndroidManifest.xml:37:9-40:75 to override.
```
这个不是解决办法？
