### ISSUE TITLE
使用这个包 pod install 失败,谁知道怎么处理吗

### ISSUE THREAD

**Issue by luobao1207** [haxibiao/react-native-qq-lib#2]
[!] No podspec found for `react-native-qq-lib` in `../node_modules/react-native-qq-lib`

**Comment by PBK-B** [comment]
> [!] No podspec found for `react-native-qq-lib` in `../node_modules/react-native-qq-lib`

@luobao1207 能给一下详细的错误吗？

**Comment by luobao1207** [comment]
![image](https://user-images.githubusercontent.com/16185136/101270305-b4aee800-37b2-11eb-90c0-ab4ca20e938d.png)
我要把这个文件改一下名称就可以了

**Comment by luobao1207** [comment]
![image](https://user-images.githubusercontent.com/16185136/101270325-db6d1e80-37b2-11eb-8282-5f7efea27f26.png)
react-native-qq.podspec 改成 react-native-qq-lib.podspec就可以了

**Comment by luobao1207** [comment]
> > [!] No podspec found for `react-native-qq-lib` in `../node_modules/react-native-qq-lib`
> 
> @luobao1207 能给一下详细的错误吗？


react-native-qq.podspec 改成 react-native-qq-lib.podspec就可以了

**Comment by PBK-B** [comment]
@luobao1207 好的，感谢提醒
