### ISSUE TITLE
> [!] No podspec found for `react-native-qq-lib` in `../node_modules/react-native-qq-lib`

### ISSUE THREAD

**Issue by luobao1207** [haxibiao/react-native-qq-lib#3]
> [!] No podspec found for `react-native-qq-lib` in `../node_modules/react-native-qq-lib`

@luobao1207 能给一下详细的错误吗？

_Originally posted by @PBK-B in https://github.com/haxibiao/react-native-qq-lib/issues/2#issuecomment-731733690_

**Comment by luobao1207** [comment]
react-native-qq.podspec 改成 react-native-qq-lib.podspec就可以了

**Comment by PBK-B** [comment]
已解决：https://github.com/haxibiao/react-native-qq-lib/issues/2
