### ISSUE TITLE
yarn add 链接拒绝 ECONNREFUSED

### ISSUE THREAD

**Issue by HaddyYang** [haxibiao/react-native-qq-lib#5]
yarn add 的时候报错如下：
error An unexpected error occurred: "https://raw.githubusercontent.com/haxibiao/react-native-qq-lib/1040ce80f45756dc8a43c59308ad0a86e670abcb/package.json: connect ECONNREFUSED 151.101.228.133:443".

这个是我设置hosts后的错误，若不设置，则提示connect ECONNREFUSED 0.0.0.0:443

**Comment by PBK-B** [comment]
@HaddyYang 试试直接 ``` yarn add react-native-qq-lib ```，包已经 push 到 npmjs.com 了

**Comment by HaddyYang** [comment]
@PBK-B  太好了，谢谢你
