### ISSUE TITLE
是否安装QQ的函数无效

### ISSUE THREAD

**Issue by HaddyYang** [haxibiao/react-native-qq-lib#6]
作者你好，我使用如下代码得到 qq installed: [null]。我使用手机真机调试，手机有安装QQ

QQAPI.isQQInstalled().then((result) => {
      console.log('qq installed: ', result);
})

**Comment by PBK-B** [comment]
@HaddyYang 我这边 android 设备真机调试正常，方便给点详细信息嘛？比如 android 版本？

**Comment by HaddyYang** [comment]
@PBK-B 我目前是用iphone测试，具体设备信息如下：
机型：iPhone 6s
系统版本：14.2
RN版本：0.63

我等下也用安卓测试看下

**Comment by HaddyYang** [comment]
@PBK-B 这个promise得到的正常结果是布尔值吗？

**Comment by PBK-B** [comment]
> @ PBK-B这个promise得到的正常结果是布尔值吗？

是的，我还没测试 ios ，下午我看看

**Comment by PBK-B** [comment]
> 作者你好，我使用如下代码得到 qq installed: [null]。我使用手机真机调试，手机有安装QQ
> 
> QQAPI.isQQInstalled().then((result) => {
> console.log('qq installed: ', result);
> })

@HaddyYang 请将 react-native-qq-lib 更新至 3.0.7 帮忙验证修复是否完成，很感谢您使用本模块并及时反馈问题，也很抱歉拖了这么久才解决。
