### ISSUE TITLE
Module RCTQQAPI requires main queue setup

### ISSUE THREAD

**Issue by HaddyYang** [haxibiao/react-native-qq-lib#7]
出现一个warning
Module RCTQQAPI requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

我的环境如下：
react-native版本是0.63.3
ios模拟器iphone11

**Comment by PBK-B** [comment]
> 出现一个warning
> Module RCTQQAPI requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
> 
> 我的环境如下：
> react-native版本是0.63.3
> ios模拟器iphone11

收到，这个稍后我试试，重现后给您答复
