### ISSUE TITLE
安卓提示没有mReactInstanceManager

### ISSUE THREAD

**Issue by HaddyYang** [haxibiao/react-native-qq-lib#8]
按照readme的说明，安卓加了
```mReactInstanceManager.onActivityResult(requestCode, resultCode, data);```
编译的时候提示没有mReactInstanceManager，这个请问如何引入？

**Comment by HaddyYang** [comment]
测试发现不需要该项配置

**Comment by PBK-B** [comment]
> 测试发现不需要该项配置

好的，我更新一下文档，感谢提醒
