### ISSUE TITLE
设备未授权（错误码：25105）

### ISSUE THREAD

**Issue by HaddyYang** [haxibiao/react-native-qq-lib#9]
在QQ互联设置应用的IOS Universal Link（校验也通过）
然后iPhone无法发起分享，提示设备未授权（错误码：25105）。
请问是否需要添加其他代码处理？

**Comment by PBK-B** [comment]
> 过）
> 然后iPhone无法发起分享，提示设备未授权（错误码

工程 plist 文件改了吗？能否提供一下视频或者截图，这个问题凭口头描述好像无法定位…

**Comment by HaddyYang** [comment]
![image](https://user-images.githubusercontent.com/19700113/106353018-72250a00-6322-11eb-968d-7f4593f45838.png)
这个是我遇到的，发起QQ分享就出现这个提示。

后来我调整了一下Universal Link，发现错误表现现象变了。又改回来配置，还是新的错误表现现象。该错误是：
发起QQ分享，QQ出现安全校验的提示，然后返回到我的App，就没反应了。

![image](https://user-images.githubusercontent.com/19700113/106353085-fa0b1400-6322-11eb-96ca-a52ac1878aae.png)

* plist文件按照readme配置了

**Comment by HaddyYang** [comment]
@PBK-B 好像我分享的图片看不到。方便的话，可以邮件联系。我的邮箱：624644925@qq.com

**Comment by PBK-B** [comment]
> @PBK-B 好像我分享的图片看不到。方便的话，可以邮件联系。我的邮箱：[624644925@qq.com](mailto:624644925@qq.com)

能看到的，不过这个问题我这边无法重现，建议联系一下腾讯开发平台的客服咨询一下，或者查阅一下文档：https://wiki.connect.qq.com/
因为这个问题从你的截图上看起来是已经跳转QQ成功了，是QQ客户端这边拒绝了操作，好像并不是 SDK 上面的问题，我猜测可能是腾讯那边做了一些设置，好像在他们后台有个测试 QQ 号的设置，不知和这个有没有什么关系。你也可以先留着这个 issue，如果解决了可以回复并且 Close 一下，谢谢

**Comment by HaddyYang** [comment]
@PBK-B 谢谢你的回复，我看看怎么解决

**Comment by HaddyYang** [comment]
@PBK-B 我发现这篇文档
https://wiki.connect.qq.com/universal-links%E9%80%82%E9%85%8Dfaq
其中就提到我说的情况。需要在continueUserActivity中处理，可能我看了该库的源码没有找到相关的设置

**Comment by HaddyYang** [comment]
@PBK-B 该问题解决了。在ios/AppDelegate.m 添加handleOpenUrl和continueUserActivity的处理，如下所示
```
#import <TencentOpenAPI/TencentOAuth.h>
#import <TencentOpenAPI/QQApiInterface.h>
#import <TencentOpenAPI/QQApiInterfaceObject.h>


- (BOOL)application:(UIApplication *)application handleOpenURL:(NSURL *)url {
  if ([TencentOAuth CanHandleOpenURL:url]) {
    return [TencentOAuth HandleOpenURL:url];
  }
  return  YES;
}

- (BOOL)application:(UIApplication *)application
  continueUserActivity:(NSUserActivity *)userActivity
  restorationHandler:(void(^)(NSArray<id<UIUserActivityRestoring>> * __nullable
  restorableObjects))restorationHandler {
  // 触发回调方法
  [RCTLinkingManager application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
  NSURL *url = userActivity.webpageURL;
  if (url && [TencentOAuth CanHandleUniversalLink:url]) {
    return [TencentOAuth HandleUniversalLink:url];
  }
  return YES;
}
```

**Comment by PBK-B** [comment]
> @PBK-B 该问题解决了。在ios/AppDelegate.m 添加handleOpenUrl和continueUserActivity的处理，如下所示
> 
> ```
> #import <TencentOpenAPI/TencentOAuth.h>
> #import <TencentOpenAPI/QQApiInterface.h>
> #import <TencentOpenAPI/QQApiInterfaceObject.h>
> 
> 
> - (BOOL)application:(UIApplication *)application handleOpenURL:(NSURL *)url {
>   if ([TencentOAuth CanHandleOpenURL:url]) {
>     return [TencentOAuth HandleOpenURL:url];
>   }
>   return  YES;
> }
> 
> - (BOOL)application:(UIApplication *)application
>   continueUserActivity:(NSUserActivity *)userActivity
>   restorationHandler:(void(^)(NSArray<id<UIUserActivityRestoring>> * __nullable
>   restorableObjects))restorationHandler {
>   // 触发回调方法
>   [RCTLinkingManager application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
>   NSURL *url = userActivity.webpageURL;
>   if (url && [TencentOAuth CanHandleUniversalLink:url]) {
>     return [TencentOAuth HandleUniversalLink:url];
>   }
>   return YES;
> }
> ```

好的收到，我这边没有重现的问题可能是因为我对接微信sdk时已经实现了该回调，再次感谢您的支持，我更新一下对接文档。
